import {
  DollarSign,
  Landmark,
  GraduationCap,
  Heart,
  Users,
  Shield,
  TrendingUp,
  Scale,
  Factory,
  Megaphone,
  HandHeart,
  FolderKanban,
  Building2,
  Cpu,
  Building,
  Briefcase,
  HardHat,
  UtensilsCrossed,
  Brain,
  Coins,
  FlaskConical,
  ClipboardCheck,
  LucideIcon,
} from 'lucide-react';

export interface Industry {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  icon: LucideIcon;
  industriesWeSupport: string[];
  rolesWeRecruit: string[];
  staffingSolutions: string[];
}

export const industries: Industry[] = [
  {
    slug: 'accounting-finance',
    name: 'Accounting & Finance',
    shortName: 'Accounting & Finance',
    description: 'Expert recruitment for financial professionals across all industries.',
    longDescription: 'Blue Chip Staffing partners with organizations nationwide to recruit accounting and finance professionals. From staff accountants to CFOs, we deliver talent that drives financial excellence.',
    icon: DollarSign,
    industriesWeSupport: [
      'Public Accounting Firms',
      'Corporate Finance Departments',
      'Financial Services',
      'Investment Management',
      'Banking Institutions',
      'Insurance Companies',
      'Healthcare Organizations',
      'Manufacturing',
      'Technology Companies',
      'Nonprofit Organizations',
    ],
    rolesWeRecruit: [
      'Staff Accountant',
      'Senior Accountant',
      'Accounting Manager',
      'Controller',
      'Assistant Controller',
      'Chief Financial Officer',
      'Financial Analyst',
      'Senior Financial Analyst',
      'Finance Manager',
      'Director of Finance',
      'Tax Accountant',
      'Audit Manager',
      'Budget Analyst',
      'Treasury Analyst',
      'Accounts Payable Manager',
      'Accounts Receivable Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'banking-mortgage',
    name: 'Banking & Mortgage',
    shortName: 'Banking & Mortgage',
    description: 'Specialized staffing for banking, lending, and mortgage professionals.',
    longDescription: 'Blue Chip Staffing supports banking and mortgage institutions with experienced professionals who understand regulatory requirements and customer service excellence.',
    icon: Landmark,
    industriesWeSupport: [
      'Commercial Banks',
      'Credit Unions',
      'Mortgage Lenders',
      'Investment Banks',
      'Financial Technology',
      'Consumer Lending',
      'Private Banking',
      'Wealth Management',
    ],
    rolesWeRecruit: [
      'Loan Officer',
      'Mortgage Underwriter',
      'Bank Teller',
      'Branch Manager',
      'Credit Analyst',
      'Loan Processor',
      'Compliance Officer',
      'Risk Manager',
      'Commercial Lender',
      'Private Banker',
      'Relationship Manager',
      'Operations Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'education',
    name: 'Education',
    shortName: 'Education',
    description: 'Staffing solutions for K-12, higher education, and educational organizations.',
    longDescription: 'Blue Chip Staffing partners with educational institutions to recruit administrators, educators, and support staff who are committed to student success.',
    icon: GraduationCap,
    industriesWeSupport: [
      'K-12 Schools',
      'Colleges and Universities',
      'Charter Schools',
      'Private Schools',
      'Educational Technology',
      'Nonprofit Education',
      'Vocational Training',
      'Corporate Training',
    ],
    rolesWeRecruit: [
      'School Administrator',
      'Principal',
      'Dean',
      'Registrar',
      'Admissions Director',
      'Financial Aid Director',
      'Academic Advisor',
      'Curriculum Coordinator',
      'IT Director',
      'HR Director',
      'Facilities Manager',
      'Development Officer',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'healthcare',
    name: 'Healthcare',
    shortName: 'Healthcare',
    description: 'Healthcare staffing for clinical and administrative professionals.',
    longDescription: 'Blue Chip Staffing provides healthcare organizations with qualified professionals who deliver exceptional patient care and operational excellence.',
    icon: Heart,
    industriesWeSupport: [
      'Hospitals',
      'Medical Centers',
      'Outpatient Clinics',
      'Long-Term Care Facilities',
      'Home Health Agencies',
      'Pharmaceutical Companies',
      'Medical Device Companies',
      'Health Insurance',
      'Telehealth Providers',
    ],
    rolesWeRecruit: [
      'Healthcare Administrator',
      'Practice Manager',
      'Medical Office Manager',
      'Revenue Cycle Manager',
      'Health Information Manager',
      'Compliance Officer',
      'Quality Assurance Manager',
      'Patient Services Director',
      'Medical Billing Specialist',
      'Medical Coder',
      'Clinical Coordinator',
      'Nurse Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'human-resources',
    name: 'Human Resources',
    shortName: 'Human Resources',
    description: 'HR professionals who build great workplace cultures.',
    longDescription: 'Blue Chip Staffing recruits HR professionals who help organizations attract, develop, and retain top talent while maintaining compliance and culture.',
    icon: Users,
    industriesWeSupport: [
      'Corporate HR Departments',
      'HR Consulting Firms',
      'Staffing Agencies',
      'Professional Employer Organizations',
      'Technology Companies',
      'Healthcare Organizations',
      'Financial Services',
      'Manufacturing',
    ],
    rolesWeRecruit: [
      'HR Assistant',
      'HR Generalist',
      'HR Manager',
      'HR Director',
      'VP of Human Resources',
      'Chief People Officer',
      'Talent Acquisition Specialist',
      'Recruiter',
      'Compensation Analyst',
      'Benefits Administrator',
      'HRIS Analyst',
      'Employee Relations Specialist',
      'Training and Development Manager',
      'Organizational Development Specialist',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'insurance',
    name: 'Insurance',
    shortName: 'Insurance',
    description: 'Insurance industry staffing from underwriting to claims.',
    longDescription: 'Blue Chip Staffing provides insurance companies with professionals who understand risk management, compliance, and customer service.',
    icon: Shield,
    industriesWeSupport: [
      'Property & Casualty Insurance',
      'Life Insurance',
      'Health Insurance',
      'Reinsurance',
      'Insurance Brokerages',
      'InsurTech Companies',
      'Risk Management Firms',
    ],
    rolesWeRecruit: [
      'Underwriter',
      'Claims Adjuster',
      'Claims Examiner',
      'Actuary',
      'Insurance Agent',
      'Account Manager',
      'Loss Control Specialist',
      'Risk Analyst',
      'Compliance Officer',
      'Policy Analyst',
      'Sales Manager',
      'Branch Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'investment-management',
    name: 'Investment Management & Capital Markets',
    shortName: 'Investment Management',
    description: 'Staffing for investment firms and capital market professionals.',
    longDescription: 'Blue Chip Staffing partners with investment management firms to recruit professionals who drive portfolio performance and client relationships.',
    icon: TrendingUp,
    industriesWeSupport: [
      'Asset Management Firms',
      'Hedge Funds',
      'Private Equity',
      'Venture Capital',
      'Mutual Fund Companies',
      'Pension Funds',
      'Family Offices',
      'Wealth Management',
    ],
    rolesWeRecruit: [
      'Investment Analyst',
      'Portfolio Manager',
      'Research Analyst',
      'Trader',
      'Risk Manager',
      'Compliance Officer',
      'Operations Manager',
      'Client Relationship Manager',
      'Fund Accountant',
      'Performance Analyst',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'legal',
    name: 'Legal/Law',
    shortName: 'Legal',
    description: 'Legal staffing for law firms and corporate legal departments.',
    longDescription: 'Blue Chip Staffing provides law firms and corporate legal departments with qualified professionals who support legal operations and client service.',
    icon: Scale,
    industriesWeSupport: [
      'Law Firms',
      'Corporate Legal Departments',
      'Government Agencies',
      'Nonprofit Organizations',
      'Legal Technology Companies',
      'Compliance Departments',
    ],
    rolesWeRecruit: [
      'Paralegal',
      'Legal Secretary',
      'Legal Assistant',
      'Legal Administrator',
      'Office Manager',
      'Compliance Specialist',
      'Contracts Manager',
      'Legal Operations Manager',
      'eDiscovery Specialist',
      'Legal Billing Specialist',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'manufacturing',
    name: 'Manufacturing',
    shortName: 'Manufacturing',
    description: 'Manufacturing staffing from operations to executive leadership.',
    longDescription: 'Blue Chip Staffing supports manufacturing organizations with professionals who drive operational excellence, quality, and continuous improvement.',
    icon: Factory,
    industriesWeSupport: [
      'Discrete Manufacturing',
      'Process Manufacturing',
      'Automotive',
      'Aerospace',
      'Consumer Goods',
      'Industrial Equipment',
      'Electronics',
      'Food & Beverage',
    ],
    rolesWeRecruit: [
      'Plant Manager',
      'Operations Manager',
      'Production Manager',
      'Quality Manager',
      'Supply Chain Manager',
      'Procurement Manager',
      'Maintenance Manager',
      'Safety Manager',
      'Continuous Improvement Manager',
      'Manufacturing Engineer',
      'Process Engineer',
      'Industrial Engineer',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'marketing',
    name: 'Marketing',
    shortName: 'Marketing',
    description: 'Marketing professionals who drive brand growth and engagement.',
    longDescription: 'Blue Chip Staffing recruits marketing professionals who help organizations build brands, generate leads, and drive business growth.',
    icon: Megaphone,
    industriesWeSupport: [
      'Marketing Agencies',
      'Corporate Marketing Departments',
      'Technology Companies',
      'Consumer Products',
      'Financial Services',
      'Healthcare',
      'Media & Entertainment',
    ],
    rolesWeRecruit: [
      'Marketing Coordinator',
      'Marketing Manager',
      'Marketing Director',
      'VP of Marketing',
      'CMO',
      'Digital Marketing Specialist',
      'Content Marketing Manager',
      'Social Media Manager',
      'Brand Manager',
      'Product Marketing Manager',
      'Demand Generation Manager',
      'Marketing Analytics Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'nonprofit',
    name: 'Nonprofit',
    shortName: 'Nonprofit',
    description: 'Mission-driven staffing for nonprofit organizations.',
    longDescription: 'Blue Chip Staffing partners with nonprofit organizations to recruit professionals who are passionate about making a difference in their communities.',
    icon: HandHeart,
    industriesWeSupport: [
      'Social Services',
      'Healthcare Nonprofits',
      'Education Nonprofits',
      'Arts & Culture',
      'Environmental Organizations',
      'Foundations',
      'Religious Organizations',
      'Advocacy Groups',
    ],
    rolesWeRecruit: [
      'Executive Director',
      'Development Director',
      'Program Manager',
      'Grant Writer',
      'Fundraising Manager',
      'Volunteer Coordinator',
      'Communications Manager',
      'Finance Director',
      'Operations Manager',
      'Board Liaison',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'project-management',
    name: 'Project Management',
    shortName: 'Project Management',
    description: 'Project managers who deliver results on time and on budget.',
    longDescription: 'Blue Chip Staffing recruits project management professionals who drive successful project delivery across industries.',
    icon: FolderKanban,
    industriesWeSupport: [
      'Technology',
      'Construction',
      'Healthcare',
      'Financial Services',
      'Manufacturing',
      'Consulting',
      'Government',
      'Telecommunications',
    ],
    rolesWeRecruit: [
      'Project Coordinator',
      'Project Manager',
      'Senior Project Manager',
      'Program Manager',
      'Portfolio Manager',
      'PMO Director',
      'Scrum Master',
      'Agile Coach',
      'Business Analyst',
      'Change Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    shortName: 'Real Estate',
    description: 'Real estate professionals for property management and development.',
    longDescription: 'Blue Chip Staffing supports real estate organizations with professionals who manage properties, drive transactions, and oversee development projects.',
    icon: Building,
    industriesWeSupport: [
      'Commercial Real Estate',
      'Residential Real Estate',
      'Property Management',
      'Real Estate Development',
      'REITs',
      'Real Estate Investment',
      'Facility Management',
    ],
    rolesWeRecruit: [
      'Property Manager',
      'Asset Manager',
      'Leasing Manager',
      'Acquisitions Analyst',
      'Development Manager',
      'Construction Manager',
      'Facilities Manager',
      'Real Estate Analyst',
      'Portfolio Manager',
      'Regional Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'tech-it',
    name: 'Tech/IT',
    shortName: 'Technology',
    description: 'Technology staffing from developers to IT executives.',
    longDescription: 'Blue Chip Staffing provides technology organizations with skilled professionals who drive innovation and digital transformation.',
    icon: Cpu,
    industriesWeSupport: [
      'Software Companies',
      'IT Services',
      'FinTech',
      'HealthTech',
      'E-Commerce',
      'Cybersecurity',
      'Cloud Computing',
      'Enterprise Technology',
    ],
    rolesWeRecruit: [
      'Software Engineer',
      'Full Stack Developer',
      'Frontend Developer',
      'Backend Developer',
      'DevOps Engineer',
      'Data Engineer',
      'Data Scientist',
      'IT Manager',
      'IT Director',
      'CTO',
      'Systems Administrator',
      'Network Engineer',
      'Security Engineer',
      'QA Engineer',
      'Product Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'government',
    name: 'Government',
    shortName: 'Government',
    description: 'Staffing solutions for government agencies and contractors.',
    longDescription: 'Blue Chip Staffing supports government agencies and contractors with professionals who understand public sector requirements and compliance.',
    icon: Building2,
    industriesWeSupport: [
      'Federal Agencies',
      'State Government',
      'Local Government',
      'Government Contractors',
      'Defense',
      'Public Utilities',
    ],
    rolesWeRecruit: [
      'Program Manager',
      'Project Manager',
      'Business Analyst',
      'Policy Analyst',
      'Budget Analyst',
      'Contracts Specialist',
      'Compliance Officer',
      'IT Specialist',
      'Administrative Officer',
      'Human Resources Specialist',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Direct Hire Placement'],
  },
  // NEW INDUSTRIES (7 from Tom's document)
  {
    slug: 'corporate-professional',
    name: 'Corporate & Professional',
    shortName: 'Corporate',
    description: 'Corporate staffing for business operations and administrative excellence.',
    longDescription: 'Blue Chip Staffing partners with organizations nationwide to recruit professionals responsible for business operations, financial management, administrative support, and strategic leadership. We support companies across all 50 states with corporate professionals who help organizations operate efficiently, manage growth, and support executive teams.',
    icon: Briefcase,
    industriesWeSupport: [
      'Healthcare Organizations',
      'Financial Services',
      'Insurance Companies',
      'Technology Companies',
      'Manufacturing Organizations',
      'Pharmaceutical and Life Sciences Companies',
      'Biotechnology Firms',
      'Retail and Consumer Products',
      'Logistics and Supply Chain Companies',
      'Professional Services Firms',
      'Real Estate and Property Management',
      'Construction and Engineering Firms',
      'Energy and Utilities',
      'Telecommunications',
      'Government Contractors',
      'Nonprofit Organizations',
    ],
    rolesWeRecruit: [
      'Administrative Assistant',
      'Executive Assistant',
      'Office Manager',
      'Operations Coordinator',
      'Operations Manager',
      'Business Operations Manager',
      'Project Coordinator',
      'Project Manager',
      'Program Manager',
      'Human Resources Assistant',
      'Human Resources Generalist',
      'Human Resources Manager',
      'Talent Acquisition Specialist',
      'Director of Human Resources',
      'Staff Accountant',
      'Senior Accountant',
      'Accounting Manager',
      'Controller',
      'Chief Financial Officer',
      'Financial Analyst',
      'Finance Manager',
      'Director of Finance',
      'Customer Success Manager',
      'Account Manager',
      'Procurement Specialist',
      'Compliance Specialist',
      'Business Analyst',
      'Director of Operations',
      'Vice President of Operations',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'construction',
    name: 'Construction',
    shortName: 'Construction',
    description: 'Construction staffing from project managers to field leadership.',
    longDescription: 'Blue Chip Staffing supports construction organizations across the United States with experienced professionals who help manage projects, maintain safety standards, and keep operations running efficiently. We provide construction staffing services in all 50 states and partner with organizations ranging from regional contractors to national construction firms.',
    icon: HardHat,
    industriesWeSupport: [
      'Commercial Construction',
      'Residential Development',
      'Civil Infrastructure',
      'Industrial Construction',
      'Energy and Utility Projects',
      'Government and Public Works',
      'Engineering and Architecture Firms',
      'Real Estate Development',
    ],
    rolesWeRecruit: [
      'Project Manager',
      'Construction Manager',
      'Superintendent',
      'Safety Coordinator',
      'Safety Manager',
      'Estimator',
      'Civil Engineer',
      'Field Engineer',
      'Project Coordinator',
      'Director of Construction',
      'Construction Scheduler',
      'Construction Inspector',
      'Surveyor',
      'Structural Engineer',
      'Electrical Engineer',
      'Mechanical Engineer',
      'Cost Estimator',
      'Procurement Manager',
      'Construction Accountant',
      'Contracts Administrator',
      'Permitting Specialist',
      'Quality Control Inspector',
      'Environmental Compliance Specialist',
      'BIM Specialist',
      'Construction Operations Manager',
      'Vice President of Construction',
      'Chief Operating Officer',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'hospitality',
    name: 'Hospitality',
    shortName: 'Hospitality',
    description: 'Hospitality staffing for hotels, restaurants, and event services.',
    longDescription: 'Blue Chip Staffing partners with hospitality organizations nationwide to provide professionals who support daily operations, customer service, and management leadership. We recruit hospitality talent in all 50 states and work with organizations ranging from local restaurant groups to national hotel brands.',
    icon: UtensilsCrossed,
    industriesWeSupport: [
      'Hotels and Resorts',
      'Restaurant Groups',
      'Event and Convention Services',
      'Travel and Tourism',
      'Luxury Hospitality',
      'Catering Companies',
      'Casino and Gaming Operations',
      'Hospitality Management Companies',
    ],
    rolesWeRecruit: [
      'Restaurant Manager',
      'Food and Beverage Manager',
      'Front Desk Associate',
      'Guest Services Manager',
      'Hotel General Manager',
      'Concierge',
      'Banquet Manager',
      'Catering Manager',
      'Event Coordinator',
      'Reservations Specialist',
      'Night Auditor',
      'Executive Chef',
      'Sous Chef',
      'Kitchen Manager',
      'Bar Manager',
      'Bartender',
      'Sommelier',
      'Director of Hospitality Operations',
      'Regional Hospitality Manager',
      'Director of Food and Beverage',
      'Vice President of Hospitality Operations',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'artificial-intelligence',
    name: 'Artificial Intelligence',
    shortName: 'AI',
    description: 'AI and machine learning talent for innovative technology companies.',
    longDescription: 'Blue Chip Staffing partners with technology organizations developing artificial intelligence platforms and advanced data systems. We recruit AI professionals nationwide across all 50 states and support companies building innovative technology solutions.',
    icon: Brain,
    industriesWeSupport: [
      'Artificial Intelligence Platforms',
      'Enterprise Software',
      'Financial Technology',
      'Robotics and Automation',
      'Healthcare Technology',
      'Cybersecurity Technology',
      'Data and Analytics Companies',
      'Autonomous Systems',
    ],
    rolesWeRecruit: [
      'Machine Learning Engineer',
      'Artificial Intelligence Engineer',
      'Data Scientist',
      'AI Research Scientist',
      'Computer Vision Engineer',
      'NLP Engineer',
      'Data Engineer',
      'AI Architect',
      'Director of Artificial Intelligence',
      'Software Engineer',
      'Backend Engineer',
      'Frontend Engineer',
      'Full Stack Developer',
      'MLOps Engineer',
      'AI Product Manager',
      'AI Solutions Architect',
      'Robotics Engineer',
      'Cloud Engineer',
      'DevOps Engineer',
      'Data Analyst',
      'Business Intelligence Analyst',
      'Data Platform Engineer',
      'Head of Artificial Intelligence',
      'Chief Technology Officer',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'venture-capital',
    name: 'Venture Capital & Private Equity',
    shortName: 'VC & PE',
    description: 'Staffing for investment firms and portfolio company leadership.',
    longDescription: 'Blue Chip Staffing partners with venture capital firms, private equity firms, and their portfolio companies to recruit professionals who help drive operational growth and financial performance. We support organizations across all 50 states.',
    icon: Coins,
    industriesWeSupport: [
      'Private Equity Firms',
      'Venture Capital Firms',
      'Growth Equity Funds',
      'Portfolio Companies',
      'Corporate Development Teams',
      'Technology Investments',
      'Healthcare Investments',
      'Manufacturing Investments',
    ],
    rolesWeRecruit: [
      'Investment Analyst',
      'Private Equity Associate',
      'Executive Assistant',
      'Vice President of Investments',
      'Portfolio Operations Manager',
      'Strategy Manager',
      'Finance Director',
      'Controller',
      'Chief Financial Officer',
      'Chief Operating Officer',
      'Chief Executive Officer',
      'Investment Manager',
      'Investment Director',
      'Corporate Development Analyst',
      'Corporate Development Manager',
      'Financial Analyst',
      'Senior Financial Analyst',
      'Fund Accountant',
      'Investor Relations Manager',
      'Investor Relations Associate',
      'Portfolio Company CFO',
      'Portfolio Company COO',
      'Strategy Director',
      'Chief Strategy Officer',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'life-sciences',
    name: 'Life Sciences',
    shortName: 'Life Sciences',
    description: 'Life sciences staffing for pharma, biotech, and research organizations.',
    longDescription: 'Blue Chip Staffing supports life sciences organizations across the United States by identifying professionals who contribute to research, clinical trials, regulatory compliance, and manufacturing operations. We provide staffing support across all 50 states and partner with pharmaceutical, biotechnology, and research organizations.',
    icon: FlaskConical,
    industriesWeSupport: [
      'Pharmaceutical Companies',
      'Biotechnology Firms',
      'Clinical Research Organizations',
      'Medical Device Companies',
      'Contract Research Organizations',
      'Diagnostic Laboratories',
      'Research Institutions',
      'Healthcare Technology',
    ],
    rolesWeRecruit: [
      'Bioinformatics Scientist',
      'Clinical Research Associate',
      'Clinical Trial Manager',
      'Clinical Laboratory Technologist',
      'Regulatory Affairs Specialist',
      'Quality Assurance Manager',
      'Quality Control Analyst',
      'Validation Engineer',
      'Manufacturing Manager',
      'Director of Clinical Operations',
      'Microbiologist',
      'Clinical Research Scientist',
      'Manufacturing Engineer',
      'Molecular Biologist',
      'Biochemist',
      'Pharmacologist',
      'Medicinal Chemist',
      'Research Associate',
      'Laboratory Manager',
      'Biostatistician',
      'Clinical Data Manager',
      'Pharmacovigilance Specialist',
      'Drug Safety Scientist',
      'GMP Compliance Specialist',
      'Bioprocess Engineer',
      'Process Development Scientist',
      'Chief Scientific Officer',
      'Chief Executive Officer',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
  {
    slug: 'quality-control',
    name: 'Quality Control & Quality Assurance',
    shortName: 'QC & QA',
    description: 'QC/QA professionals for manufacturing and regulated industries.',
    longDescription: 'Blue Chip Staffing partners with organizations nationwide to recruit professionals responsible for quality systems, regulatory compliance, product integrity, and manufacturing oversight. We support companies across all 50 states with quality professionals who help ensure products meet regulatory, safety, and performance standards.',
    icon: ClipboardCheck,
    industriesWeSupport: [
      'Pharmaceutical Manufacturing',
      'Biotechnology',
      'Medical Device Manufacturing',
      'Food and Beverage Production',
      'Chemical Manufacturing',
      'Cosmetics and Personal Care',
      'Automotive Manufacturing',
      'Aerospace and Defense',
      'Electronics Manufacturing',
      'Consumer Products',
      'Packaging and Materials Manufacturing',
      'Nutraceutical and Supplement Manufacturing',
      'Industrial Manufacturing',
      'Environmental Testing Laboratories',
    ],
    rolesWeRecruit: [
      'Quality Control Analyst',
      'Quality Control Technician',
      'Quality Assurance Specialist',
      'Quality Assurance Associate',
      'Quality Assurance Manager',
      'Quality Control Manager',
      'Quality Systems Specialist',
      'Quality Systems Manager',
      'Quality Engineer',
      'Senior Quality Engineer',
      'Supplier Quality Engineer',
      'Manufacturing Quality Engineer',
      'Validation Engineer',
      'Validation Specialist',
      'GMP Quality Specialist',
      'GMP Compliance Specialist',
      'Quality Compliance Manager',
      'Regulatory Affairs Specialist',
      'Quality Auditor',
      'Quality Inspector',
      'Director of Quality Assurance',
      'Director of Quality Control',
      'CAPA Specialist',
      'Risk Management Specialist',
      'Laboratory Quality Manager',
    ],
    staffingSolutions: ['Contract Staffing', 'Contract to Hire', 'Managed Services', 'Payrolling Services', 'Direct Hire Placement', 'Executive Search'],
  },
];

export function getIndustryBySlug(slug: string): Industry | undefined {
  return industries.find(industry => industry.slug === slug);
}

export function getAllIndustrySlugs(): string[] {
  return industries.map(industry => industry.slug);
}
